[package]
name = "pickme-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.33", features = ["persistence", "wayland"] }
rand = "0.8.5"
rfd = "0.15.4"
serde = "1.0.203"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
